/* HABILITAR LA SALIDA A LA PANTALL */
SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE(100);
  DBMS_OUTPUT.PUT_LINE('AAAAAA' || 'XXXXX');
END;

/******************************************************************************/
/* PONER TU NOMBRE Y APELLIDOS EN PANTALLA */
SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE('NOMBRE(S):'||'JOLBERTH ALBERTO');
  DBMS_OUTPUT.PUT_LINE('APELLIDO(S):'||'REYES LOPEZ');
END;

/******************************************************************************/
/***** VARIABLES *****/
/* PONER TU NOMBRE Y APELLIDOS EN PANTALLA */
SET SERVEROUTPUT ON;

DECLARE
  NAME     VARCHAR2(100);
  LASTNAME VARCHAR2(100);
BEGIN
  NAME := 'JOLBERTH ALBERTO';
  LASTNAME := 'REYES LOPEZ';
  DBMS_OUTPUT.PUT_LINE('VARIABLE NOMBRE(S):'||NAME);
  DBMS_OUTPUT.PUT_LINE('VARIABLE APELLIDO(S):'||LASTNAME);
END;

/***** CONSTANTES Y NULL *****/
SET SERVEROUTPUT ON;

DECLARE
  X CONSTANT NUMBER := 10;
  Z NUMBER NOT NULL := 20;
BEGIN
  Z := 30;
  DBMS_OUTPUT.PUT_LINE(X);
  DBMS_OUTPUT.PUT_LINE(Z);
END;


