/******************************************************************************/
/***** CREAR OBJETOS DECLARACION EN PL/SQL *****/
-- CREAR CABECERA DEL OBJETO
CREATE OR REPLACE TYPE PRODUCTO AS OBJECT(
  -- ATRIBUTOS
  CODIGO NUMBER,
  NOMBRE VARCHAR2(100),
  PRECIO NUMBER,
  
  -- METODOS
  MEMBER FUNCTION VER_PRODUCTO RETURN VARCHAR2,
  MEMBER FUNCTION VER_PRECIO RETURN NUMBER,
  MEMBER PROCEDURE CAMBIAR_PRECIO(PVP NUMBER)
);
/

--PARA BORRAR OBJETO
DROP TYPE PRODUCTO;