/* HABILITAR LA SALIDA A LA PANTALL */
SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE(100);
  DBMS_OUTPUT.PUT_LINE('AAAAAA' || 'XXXXX');
END;

/******************************************************************************/
/* PONER TU NOMBRE Y APELLIDOS EN PANTALLA */
SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE('NOMBRE(S):'||'JOLBERTH ALBERTO');
  DBMS_OUTPUT.PUT_LINE('APELLIDO(S):'||'REYES LOPEZ');
END;

/******************************************************************************/
/***** VARIABLES *****/
/* PONER TU NOMBRE Y APELLIDOS EN PANTALLA */
SET SERVEROUTPUT ON;

DECLARE
  NAME     VARCHAR2(100);
  LASTNAME VARCHAR2(100);
BEGIN
  NAME := 'JOLBERTH ALBERTO';
  LASTNAME := 'REYES LOPEZ';
  DBMS_OUTPUT.PUT_LINE('VARIABLE NOMBRE(S):'||NAME);
  DBMS_OUTPUT.PUT_LINE('VARIABLE APELLIDO(S):'||LASTNAME);
END;

/***** CONSTANTES Y NULL *****/
SET SERVEROUTPUT ON;

DECLARE
  X CONSTANT NUMBER := 10;
  Z NUMBER NOT NULL := 20;
BEGIN
  Z := 30;
  DBMS_OUTPUT.PUT_LINE(X);
  DBMS_OUTPUT.PUT_LINE(Z);
END;

/******************************************************************************/
/***** BLOQUES ANIDADOS *****/
SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE('EN EL PRIMER BLOQUES');
  DECLARE
    X NUMBER := 10;
  BEGIN
    DBMS_OUTPUT.PUT_LINE(X);
  END;
END;

/***** BLOQUES ANIDADOS - AMBITO DE VARIABLES *****/
SET SERVEROUTPUT ON;

DECLARE
  X NUMBER := 20; -- VARIABLE GLOBAL
  Z NUMBER := 30;
BEGIN
  DBMS_OUTPUT.PUT_LINE('X := '||X);
  DECLARE
    X NUMBER := 10; -- VARIABLE LOCAL
  BEGIN
    DBMS_OUTPUT.PUT_LINE('X := '||X);
    DBMS_OUTPUT.PUT_LINE('Z := '||Z);
  END;
END;

/******************************************************************************/
/***** FUNCIONES *****/
SET SERVEROUTPUT ON;

DECLARE
  X     VARCHAR2(50);
  FECHA DATE;
  Z NUMBER := 109.90;
BEGIN
  X := 'Ejemplo';
  FECHA := SYSDATE;
  
  DBMS_OUTPUT.PUT_LINE('SUBSTR: '||SUBSTR(X,1,3)); -- ME DEVOLVERA LOS PRIMEROS 3 CARACTERES DE 'Ejemplo'
  DBMS_OUTPUT.PUT_LINE('UPPER: '||UPPER(X)); -- CONVIERTE A MAYUSCULA LA VARIABLE X
  DBMS_OUTPUT.PUT_LINE('SYSDATE: '||FECHA); -- FECHA ACTUAL
  DBMS_OUTPUT.PUT_LINE('FLOOR: '||FLOOR(Z)); -- APROXIMAR NUMERO
END;


