/******************************************************************************/
/***** PACKAGES DE PL/SQL *****/
CREATE OR REPLACE PACKAGE PACK1
IS
  V1 NUMBER;
  V2 VARCHAR2(100);
END;

SET SERVEROUTPUT ON;

BEGIN
  PACK1.V1 := 100;
  PACK1.V2 := 'PROGRAMACION BD';
  DBMS_OUTPUT.PUT_LINE(PACK1.V1);
  DBMS_OUTPUT.PUT_LINE(PACK1.V2);
END;

/***** AMBITO DE LAS VARIABLES PACKAGES DE PL/SQL *****/
CREATE OR REPLACE PACKAGE PACK1
IS
  V1 NUMBER := 10;
  V2 VARCHAR2(100);
END;

SET SERVEROUTPUT ON;

BEGIN
  PACK1.V1 := PACK1.V1+10;
  PACK1.V2 := 'PROGRAMACION BD';
  DBMS_OUTPUT.PUT_LINE(PACK1.V1);
  DBMS_OUTPUT.PUT_LINE(PACK1.V2);
END;

/***** CREAR UN CUERPO DE UN PACKAGE DE PL/SQL *****/
-- CREANDO LA CABECERA DEL PACKAGE
CREATE OR REPLACE PACKAGE PACK1
IS
  PROCEDURE CONVERT (NAME VARCHAR2, CONVERSION_TYPE CHAR);
END;
/

-- CREANDO EL CUERPO (BODY) DEL PACKAGE
-- REPROGRAMAR LOS PROCESOS CREADOS EN LA CABECERA DEL PACKAGE
CREATE OR REPLACE PACKAGE BODY PACK1
IS
  -- SOLO SE UTILIZARA DENTRO DEL PROCEDIMIENTO CONVERT, LO CUAL NO SERA PUBLICA LA FUNCION, POR ESO NO SE AGREGO EN LA CABECERA DEL PACKAGE
  FUNCTION UP(NAME VARCHAR2)
  RETURN VARCHAR2
  IS
  BEGIN
    RETURN UPPER(NAME);
  END UP;
  
  -- SOLO SE UTILIZARA DENTRO DEL PROCEDIMIENTO CONVERT, LO CUAL NO SERA PUBLICA LA FUNCION, POR ESO NO SE AGREGO EN LA CABECERA DEL PACKAGE
  FUNCTION DO(NAME VARCHAR2)
  RETURN VARCHAR2
  IS
  BEGIN
    RETURN LOWER(NAME);
  END DO;
  
  -- ESTE PROCEDIMIENTO SE UTILIZARA DE FORMA PUBLICA, POR ESO SE AGREGO EN LA CABECERA DEL PACKAGE
  PROCEDURE CONVERT(NAME VARCHAR2, CONVERSION_TYPE CHAR)
  IS
  BEGIN
    IF CONVERSION_TYPE='U' THEN
      DBMS_OUTPUT.PUT_LINE(UP(NAME));
    ELSIF CONVERSION_TYPE='L' THEN
      DBMS_OUTPUT.PUT_LINE(DO(NAME));
    ELSE
      DBMS_OUTPUT.PUT_LINE('EL PARAMETRO DEBE SER U o L');
    END IF;
  END CONVERT;
  
END PACK1;
/

-- EJECUTANDO EL PROCEDIMIENTO
SET SERVEROUTPUT ON;

BEGIN
  PACK1.CONVERT('Estoy Programando', 'L');
END;