/******************************************************************************/
/***** SELECT INTO - PRACTICA *****/
/* Realiza los siguientes ejemplos. Usa %ROWTYPE y %TYPE */
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID=100 ORDER BY SALARY DESC;
/* 1. PRÁCTICA 1
      • Crear un bloque PL/SQL que devuelva al salario máximo del
        departamento 100 y lo deje en una variable denominada salario_maximo
        y la visualice.
*/
SET SERVEROUTPUT ON;

DECLARE
  SALARIO_MAXIMO EMPLOYEES.SALARY%TYPE;
BEGIN
  SELECT MAX(SALARY) INTO SALARIO_MAXIMO
  FROM EMPLOYEES WHERE DEPARTMENT_ID=100;
  DBMS_OUTPUT.PUT_LINE('EL SALARIO MAXIMO DEL DEPARTAMENT_ID 100 ES: '||SALARIO_MAXIMO);
END;

/* 2. PRÁCTICA2
      • Visualizar el tipo de trabajo del empleado número 100 
*/
SET SERVEROUTPUT ON;

DECLARE
  TIPO_TRABAJO EMPLOYEES%ROWTYPE;
BEGIN
  SELECT * INTO TIPO_TRABAJO
  FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
  DBMS_OUTPUT.PUT_LINE('EL EMPLEADO '||TIPO_TRABAJO.FIRST_NAME||' '||TIPO_TRABAJO.LAST_NAME||' CON ID '||TIPO_TRABAJO.EMPLOYEE_ID||' TIENE UN TRABAJO DE '||TIPO_TRABAJO.JOB_ID);
END;

/* 3. PRÁCTICA 3
      • Crear una variable de tipo DEPARTMENT_ID y ponerla algún valor, por
        ejemplo 10.
      • Visualizar el nombre de ese departamento y el número de empleados
        que tiene, poniendo. Crear dos variables para albergar los valores.
*/
SET SERVEROUTPUT ON;

DECLARE
  DEPARTAMENTO_ID     EMPLOYEES.DEPARTMENT_ID%TYPE;
  DEPARTAMENTO_NOMBRE DEPARTMENTS.DEPARTMENT_NAME%TYPE;
  NUMERO_EMPLEADOS    NUMBER;
BEGIN
  DEPARTAMENTO_ID := 10;
  SELECT DEPARTMENTS.DEPARTMENT_NAME, COUNT(*)
  INTO DEPARTAMENTO_NOMBRE, NUMERO_EMPLEADOS
  FROM EMPLOYEES INNER JOIN DEPARTMENTS ON(EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID)
  WHERE EMPLOYEES.DEPARTMENT_ID=DEPARTAMENTO_ID
  GROUP BY DEPARTMENTS.DEPARTMENT_NAME;
  DBMS_OUTPUT.PUT_LINE('DEPARTAMENTO '||DEPARTAMENTO_NOMBRE||', tiene '||NUMERO_EMPLEADOS||' empleados.');
END;

/* 4. PRÁCTICA 4
      • Mediante dos consultas recuperar el salario máximo y el salario mínimo
        de la empresa e indicar su diferencia.
*/
SET SERVEROUTPUT ON;

DECLARE
  SALARIO_MAX EMPLOYEES.SALARY%TYPE;
  SALARIO_MIN EMPLOYEES.SALARY%TYPE;
  SALARIO_DIF EMPLOYEES.SALARY%TYPE;
BEGIN
  SELECT MAX(SALARY), MIN(SALARY) INTO SALARIO_MAX, SALARIO_MIN FROM EMPLOYEES;
  SALARIO_DIF := SALARIO_MAX-SALARIO_MIN;
  DBMS_OUTPUT.PUT_LINE('SALARIOS MAXIMO: '||SALARIO_MAX||', MINIMO: '||SALARIO_MIN);
  DBMS_OUTPUT.PUT_LINE('DEFERENCIA DE SALARIOS: '||SALARIO_DIF);
END;