/******************************************************************************/
/***** RECORDS DE PL/SQL *****/
SET SERVEROUTPUT ON;

DECLARE
  TYPE empleado IS RECORD(
    nombre  VARCHAR2(100),
    salario NUMBER,
    fecha   EMPLOYEES.HIRE_DATE%TYPE,
    datos   EMPLOYEES%ROWTYPE
  );
  
  emple1 empleado;
BEGIN
  SELECT * INTO EMPLE1.DATOS FROM EMPLOYEES
  WHERE EMPLOYEE_ID=100;
  
  EMPLE1.NOMBRE  := EMPLE1.DATOS.FIRST_NAME||' '||EMPLE1.DATOS.LAST_NAME;
  EMPLE1.SALARIO := EMPLE1.DATOS.SALARY*0.80;
  EMPLE1.FECHA   := EMPLE1.DATOS.HIRE_DATE;
  DBMS_OUTPUT.PUT_LINE(EMPLE1.NOMBRE);
  DBMS_OUTPUT.PUT_LINE(EMPLE1.SALARIO);
  DBMS_OUTPUT.PUT_LINE(EMPLE1.FECHA);
  DBMS_OUTPUT.PUT_LINE(EMPLE1.DATOS.FIRST_NAME);
END;

/******************************************************************************/
/***** INSERT Y UPDATE RECORDS DE PL/SQL *****/
CREATE TABLE REGIONES AS SELECT * FROM REGIONS WHERE REGION_ID=0;

SET SERVEROUTPUT ON;

DECLARE
  REG1 REGIONS%ROWTYPE;
BEGIN
  SELECT * INTO REG1 FROM REGIONS WHERE REGION_ID=1;
  -- INSERT
  INSERT INTO REGIONES VALUES REG1;
END;

DECLARE
  REG1 REGIONS%ROWTYPE;
BEGIN
  REG1.REGION_ID    := 1;
  REG1.REGION_NAME  := 'AUSTRALIA';
  -- UPDATE
  UPDATE REGIONES SET ROW=REG1 WHERE REGION_ID=1;
END;

/******************************************************************************/
/***** ARRAYS ASOCIATIVOS DE PL/SQL *****/
SET SERVEROUTPUT ON;

DECLARE
  TYPE DEPARTAMENTOS IS TABLE OF
    DEPARTMENTS.DEPARTMENT_NAME%TYPE
  INDEX BY PLS_INTEGER;
  
  TYPE EMPLEADOS IS TABLE OF
    EMPLOYEES%ROWTYPE
  INDEX BY PLS_INTEGER;
  
  DEPTS   DEPARTAMENTOS;
  EMPLES  EMPLEADOS;
BEGIN
  -- TIPO SIMPLE
  DEPTS(1) := 'INFORMATICA';
  DEPTS(2) := 'RRHH';
  DBMS_OUTPUT.PUT_LINE(DEPTS(1));
  DBMS_OUTPUT.PUT_LINE(DEPTS(2));
  DBMS_OUTPUT.PUT_LINE(DEPTS.LAST);
  DBMS_OUTPUT.PUT_LINE(DEPTS.FIRST);
  IF DEPTS.EXISTS(3) THEN
    DBMS_OUTPUT.PUT_LINE(DEPTS(3));
  ELSE
    DBMS_OUTPUT.PUT_LINE('ESE VALOR NO EXISTE');
  END IF;
  
  -- TIPO COMPUESTO
  SELECT * INTO EMPLES(1) FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
  DBMS_OUTPUT.PUT_LINE(EMPLES(1).FIRST_NAME);
END;

/******************************************************************************/
/***** SELECT MULTIPLES CON ARRAYS ASOCIATIVOS DE PL/SQL *****/
SET SERVEROUTPUT ON;

DECLARE
  TYPE DEPARTAMENTOS IS TABLE OF
    DEPARTMENTS%ROWTYPE
  INDEX BY PLS_INTEGER;
  
  DEPTS DEPARTAMENTOS;
BEGIN
  FOR I IN 1..10 LOOP
    SELECT * INTO DEPTS(I) FROM DEPARTMENTS WHERE DEPARTMENT_ID=I*10;
  END LOOP;
  
  FOR I IN DEPTS.FIRST..DEPTS.LAST LOOP
    DBMS_OUTPUT.PUT_LINE(DEPTS(I).DEPARTMENT_NAME);
  END LOOP;
END;