/******************************************************************************/
/***** PACKAGES DE PL/SQL *****/
CREATE OR REPLACE PACKAGE PACK1
IS
  V1 NUMBER;
  V2 VARCHAR2(100);
END;

SET SERVEROUTPUT ON;

BEGIN
  PACK1.V1 := 100;
  PACK1.V2 := 'PROGRAMACION BD';
  DBMS_OUTPUT.PUT_LINE(PACK1.V1);
  DBMS_OUTPUT.PUT_LINE(PACK1.V2);
END;