/******************************************************************************/
/***** CREAR COLUMNAS TIPO LOB *****/
CREATE TABLE PRU_LOB(
  CODIGO NUMBER,
  NOMBRE VARCHAR2(100),
  DATOS CLOB
);

DESC PRU_LOB;

ALTER TABLE PRU_LOB ADD(FOTO BLOB);

DESC PRU_LOB;

/***** EMPTY_CLOB Y EMPTY_BLOB *****/
INSERT INTO PRU_LOB VALUES(3,'JUAN',EMPTY_CLOB(), EMPTY_BLOB());

SELECT * FROM PRU_LOB;

/***** CREAR UN DIRECTORIO *****/
-- CREAR DIRECTORIO
CREATE OR REPLACE DIRECTORY FICHEROS AS '/home/jreyes/Documentos/BBDD/ORACLE/PLSQL - Avanzado/5_SECCION_FICHEROS_LOBS';

-- CONSULTAR DIRECTORIOS CREADOS
SELECT * FROM ALL_DIRECTORIES;


