/******************************************************************************/
/***** CREAR INDEX BY TABLES - ARRAYS ASOCIATIVOS *****/
SET SERVEROUTPUT ON;

DECLARE
  -- CREANDO EL PRIMER TIPO DE TABLA
  TYPE DEPARTAMENTOS IS TABLE OF DEPARTMENTS.DEPARTMENT_NAME%TYPE INDEX BY PLS_INTEGER;
  -- CREANDO EL SEGUNDO TIPO DE TABLA
  TYPE EMPLEADOS IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
  TYPE NOMBRE IS TABLE OF EMPLOYEES.FIRST_NAME%TYPE INDEX BY VARCHAR2(2);
  
  DEPTS   DEPARTAMENTOS;
  EMPLS   EMPLEADOS;
  NOMBRES NOMBRE;
BEGIN
  -- INTRODUCIR DATOS EN INDEX BY TABLE
  DEPTS(1)      := 'HOLA';
  DEPTS(2)      := 'ADIOS';
  DEPTS(50)     := 'OTRO VALOR';
  DEPTS(-10)    := 'SIGUIENTE VALOR';
  NOMBRES('AA') := 'PEDRO';
  
  DBMS_OUTPUT.PUT_LINE(DEPTS(2));
  DBMS_OUTPUT.PUT_LINE(DEPTS(-10));
  DBMS_OUTPUT.PUT_LINE(NOMBRES('AA'));
END;