/******************************************************************************/
/***** CREAR INDEX BY TABLES - ARRAYS ASOCIATIVOS *****/
SET SERVEROUTPUT ON;

DECLARE
  -- CREANDO EL PRIMER TIPO DE TABLA
  TYPE DEPARTAMENTOS IS TABLE OF DEPARTMENTS.DEPARTMENT_NAME%TYPE INDEX BY PLS_INTEGER;
  -- CREANDO EL SEGUNDO TIPO DE TABLA
  TYPE EMPLEADOS IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
  
  DEPTS DEPARTAMENTOS;
  EMPLS EMPLEADOS;
BEGIN
  
END;