/******************************************************************************/
/***** CREAR UN REF CURSOR *****/
SET SERVEROUTPUT ON;

DECLARE
  TYPE CURSOR_VARIABLE IS REF CURSOR;
  V1 CURSOR_VARIABLE;
  X1 CURSOR_VARIABLE;
  
  EMPLEADOS EMPLOYEES%ROWTYPE;
  DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN
  OPEN V1 FOR SELECT * FROM EMPLOYEES;
  FETCH V1 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.SALARY);
  CLOSE V1;
  
  OPEN V1 FOR SELECT * FROM DEPARTMENTS;
  FETCH V1 INTO DEPARTAMENTOS;
    DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
  CLOSE V1;
END;

/***** BUCLE CON CURSORES VARIABLES *****/
SET SERVEROUTPUT ON;

DECLARE
  TYPE CURSOR_VARIABLE IS REF CURSOR;
  V1 CURSOR_VARIABLE;
  X1 CURSOR_VARIABLE;
  
  EMPLEADOS EMPLOYEES%ROWTYPE;
  DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN
  OPEN V1 FOR SELECT * FROM EMPLOYEES;
  FETCH V1 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.SALARY);
  CLOSE V1;
  
  OPEN V1 FOR SELECT * FROM DEPARTMENTS;
  FETCH V1 INTO DEPARTAMENTOS;
    DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
  CLOSE V1;
  
  OPEN V1 FOR SELECT * FROM DEPARTMENTS;
  FETCH V1 INTO DEPARTAMENTOS;
    WHILE V1%FOUND LOOP
      DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
      FETCH V1 INTO DEPARTAMENTOS;
    END LOOP;
  CLOSE V1;
  
END;