/******************************************************************************/
/***** CREAR UN REF CURSOR *****/
SET SERVEROUTPUT ON;

DECLARE
  TYPE CURSOR_VARIABLE IS REF CURSOR;
  V1 CURSOR_VARIABLE;
  X1 CURSOR_VARIABLE;
  
  EMPLEADOS EMPLOYEES%ROWTYPE;
  DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN
  OPEN V1 FOR SELECT * FROM EMPLOYEES;
  FETCH V1 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.SALARY);
  CLOSE V1;
  
  OPEN V1 FOR SELECT * FROM DEPARTMENTS;
  FETCH V1 INTO DEPARTAMENTOS;
    DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
  CLOSE V1;
END;

/***** BUCLE CON CURSORES VARIABLES *****/
SET SERVEROUTPUT ON;

DECLARE
  TYPE CURSOR_VARIABLE IS REF CURSOR;
  V1 CURSOR_VARIABLE;
  X1 CURSOR_VARIABLE;
  
  EMPLEADOS EMPLOYEES%ROWTYPE;
  DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN
  OPEN V1 FOR SELECT * FROM EMPLOYEES;
  FETCH V1 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.SALARY);
  CLOSE V1;
  
  OPEN V1 FOR SELECT * FROM DEPARTMENTS;
  FETCH V1 INTO DEPARTAMENTOS;
    DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
  CLOSE V1;
  
  OPEN V1 FOR SELECT * FROM DEPARTMENTS;
  FETCH V1 INTO DEPARTAMENTOS;
    WHILE V1%FOUND LOOP
      DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
      FETCH V1 INTO DEPARTAMENTOS;
    END LOOP;
  CLOSE V1;
  
END;

/***** REF CURSORS Y TYPOS *****/
SET SERVEROUTPUT ON;

DECLARE
  TYPE C1 IS REF CURSOR RETURN DEPARTMENTS%ROWTYPE;
  V1 C1;
  DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN
  OPEN V1 FOR SELECT * FROM DEPARTMENTS WHERE DEPARTMENT_ID>150;
    FETCH V1 INTO DEPARTAMENTOS;
      WHILE V1%FOUND LOOP
        DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
        FETCH V1 INTO DEPARTAMENTOS;
      END LOOP;
    CLOSE V1;
END;

/***** REF CURSORS EN FUNCIONES *****/
-- CREAR ENCABEZADO DE PACKAGE
CREATE OR REPLACE PACKAGE PAQ1
AS
  TYPE C_VARIABLE IS REF CURSOR;
  FUNCTION DEVOLVER_DATOS(C1 IN OUT C_VARIABLE, X NUMBER) RETURN VARCHAR2;
END;

-- CREAR EL CUERPO (BODY) DE PACKAGE
CREATE OR REPLACE PACKAGE BODY PAQ1
AS
  FUNCTION DEVOLVER_DATOS(C1 IN OUT C_VARIABLE, X NUMBER)
  RETURN VARCHAR2
  AS
    DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
    EMPLEADOS EMPLOYEES%ROWTYPE;
  BEGIN
    IF X=1 THEN
      OPEN C1 FOR SELECT * FROM EMPLOYEES;
        FETCH C1 INTO EMPLEADOS;
      RETURN EMPLEADOS.FIRST_NAME;
    ELSE
      OPEN C1 FOR SELECT * FROM DEPARTMENTS;
        FETCH C1 INTO DEPARTAMENTOS;
      RETURN DEPARTAMENTOS.DEPARTMENT_NAME;
    END IF;
  END;
END;

-- EJECUTAR
SET SERVEROUTPUT ON;

DECLARE
  DATOS PAQ1.C_VARIABLE;
BEGIN
  DBMS_OUTPUT.PUT_LINE(PAQ1.DEVOLVER_DATOS(DATOS,1));
END;

/***** COMPARTIR CURSORES *****/
SET SERVEROUTPUT ON;

DECLARE
  TYPE CURSOR_VARIABLE IS REF CURSOR RETURN EMPLOYEES%ROWTYPE;
  V1 CURSOR_VARIABLE;
  V2 CURSOR_VARIABLE;
  
  EMPLEADOS EMPLOYEES%ROWTYPE;
BEGIN
  -- ABRIMOS EL CURSOR CON LA PRIMERA VARIABLE
  OPEN V1 FOR SELECT * FROM EMPLOYEES ORDER BY FIRST_NAME;
    FETCH V1 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.FIRST_NAME||' '||EMPLEADOS.SALARY);
  
  -- ASIGNAMOS V1 A V2
    V2 := V1;
    FETCH V2 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.FIRST_NAME||' '||EMPLEADOS.SALARY);
    
    FETCH V2 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.FIRST_NAME||' '||EMPLEADOS.SALARY);
    
    FETCH V2 INTO EMPLEADOS;
    DBMS_OUTPUT.PUT_LINE(EMPLEADOS.FIRST_NAME||' '||EMPLEADOS.SALARY);
  CLOSE V1;
END;

/***** SYS_REFCURSOR *****/
SET SERVEROUTPUT ON;

DECLARE
  V1 SYS_REFCURSOR;
  
  DEPARTAMENTOS DEPARTMENTS%ROWTYPE;
BEGIN
  OPEN V1 FOR SELECT * FROM DEPARTMENTS;
    FETCH V1 INTO DEPARTAMENTOS;
      WHILE V1%FOUND LOOP
        DBMS_OUTPUT.PUT_LINE(DEPARTAMENTOS.DEPARTMENT_NAME);
        FETCH V1 INTO DEPARTAMENTOS;
      END LOOP;
  CLOSE V1;
END;