/******************************************************************************/
/***** DETECTAR DEPENDENCIAS ENTRE OBJETOS *****/
--PERMITE VER MIS DEPENDENCIAS
SELECT * FROM USER_DEPENDENCIES;

-- COMPROBAR EL ESTADO DE LOS OBJETOS
SELECT * FROM USER_OBJECTS;

-- VERIFICAR CUANTOS OBJETOS ESTAN VALIDOS O INVALIDOS
SELECT STATUS, COUNT(*) FROM USER_OBJECTS GROUP BY STATUS;

-- VERIFICAR LOS OBJETOS INVALIDOS
SELECT * FROM USER_OBJECTS WHERE STATUS='INVALID';

-- CREAR LA TABLA DE PRUEBA
CREATE TABLE PRUEBA(C1 NUMBER, C2 NUMBER);

-- CREAR LA VISTA DE PRUEBA
CREATE VIEW PRUEBA_V AS SELECT C1 FROM PRUEBA;

-- ALTERNANDO EL CAMPO C1 DE LA TABLA PRUEBA
ALTER TABLE PRUEBA MODIFY C2 VARCHAR2(100);

-- ALTERNANDO EL CAMPO C1 DE LA TABLA PRUEBA
ALTER TABLE PRUEBA MODIFY C1 VARCHAR2(100);

-- ELIMINADO LA COLUMNA C1 DE LA TABLA PRUEBA
ALTER TABLE PRUEBA DROP COLUMN C1;

-- CONSULTA LOS OBJETOS DE LA TABLA PRUEBA
SELECT * FROM USER_OBJECTS WHERE OBJECT_NAME LIKE '%PRUEBA%';

