/******************************************************************************/
/***** CREAR INDEX BY TABLES - ARRAYS ASOCIATIVOS *****/
SET SERVEROUTPUT ON;

DECLARE
  -- CREANDO EL PRIMER TIPO DE TABLA
  TYPE DEPARTAMENTOS IS TABLE OF DEPARTMENTS.DEPARTMENT_NAME%TYPE INDEX BY PLS_INTEGER;
  -- CREANDO EL SEGUNDO TIPO DE TABLA
  TYPE EMPLEADOS IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
  TYPE NOMBRE IS TABLE OF EMPLOYEES.FIRST_NAME%TYPE INDEX BY VARCHAR2(2);
  
  DEPTS   DEPARTAMENTOS;
  EMPLS   EMPLEADOS;
  NOMBRES NOMBRE;
BEGIN
  -- INTRODUCIR DATOS EN INDEX BY TABLE
  DEPTS(1)      := 'HOLA';
  DEPTS(2)      := 'ADIOS';
  DEPTS(50)     := 'OTRO VALOR';
  DEPTS(-10)    := 'SIGUIENTE VALOR';
  NOMBRES('AA') := 'PEDRO';
  
  DBMS_OUTPUT.PUT_LINE(DEPTS(2));
  DBMS_OUTPUT.PUT_LINE(DEPTS(-10));
  DBMS_OUTPUT.PUT_LINE(NOMBRES('AA'));
  
  -- INTRODUCIR DATOS COMPUESTOS EN INDEX BY TABLE
  EMPLS(10).FIRST_NAME := 'SERGIO';
  
  DBMS_OUTPUT.PUT_LINE(EMPLS(10).FIRST_NAME);
END;

/***** CARGAR UN INDEX BY TABLES CON UNA TABLA - ARRAYS ASOCIATIVOS *****/
SET SERVEROUTPUT ON;

DECLARE
  -- CREANDO EL PRIMER TIPO DE TABLA
  TYPE DEPARTAMENTOS IS TABLE OF DEPARTMENTS.DEPARTMENT_NAME%TYPE INDEX BY PLS_INTEGER;
  -- CREANDO EL SEGUNDO TIPO DE TABLA
  TYPE EMPLEADOS IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY PLS_INTEGER;
  TYPE NOMBRE IS TABLE OF EMPLOYEES.FIRST_NAME%TYPE INDEX BY VARCHAR2(2);
  
  DEPTS   DEPARTAMENTOS;
  EMPLS   EMPLEADOS;
  NOMBRES NOMBRE;
  
  -- RELLENANDO EL TYPE DEPARTAMENTOS POR MEDIO DE UN CURSOR
  CURSOR CUR_DEPT IS SELECT * FROM DEPARTMENTS;
  X PLS_INTEGER := 1;
  
  CURSOR CUR_EMP IS SELECT * FROM EMPLOYEES WHERE SALARY > 5000;
  Z PLS_INTEGER := 1;
BEGIN
  -- CARGA DE BUCLE PARA LLENAR LOS DEPARTAMENTOS
  FOR DEPT1 IN CUR_DEPT LOOP
    DEPTS(X) := DEPT1.DEPARTMENT_NAME;
    X := X+1;
  END LOOP;
  
  -- CARGA DE BUCLE PARA VISUALIZAR LOS DEPARTAMENTOS
  FOR I IN 1..X-1 LOOP
    DBMS_OUTPUT.PUT_LINE(DEPTS(I));
  END LOOP;
  
  -- INTRODUCIR DATOS COMPUESTOS EN INDEX BY TABLE
  DBMS_OUTPUT.PUT_LINE('CARGA DE INDEX TABLE - DATOS COMPUESTOS');
  -- CARGA DE BUCLE PARA LLENAR LOS EMPLEADOS
  FOR EMP1 IN CUR_EMP LOOP
    EMPLS(Z) := EMP1;
    Z := Z+1;
  END LOOP;
  
  -- CARGA DE BUCLE PARA VISUALIZAR LOS EMPLEADOS
  FOR J IN 1..Z-1 LOOP
    DBMS_OUTPUT.PUT_LINE(EMPLS(J).FIRST_NAME||' '||EMPLS(J).SALARY);
  END LOOP;
  
END;
