/******************************************************************************/
/***** DETECTAR DEPENDENCIAS ENTRE OBJETOS *****/
--PERMITE VER MIS DEPENDENCIAS
SELECT * FROM USER_DEPENDENCIES;

-- COMPROBAR EL ESTADO DE LOS OBJETOS
SELECT * FROM USER_OBJECTS;

-- VERIFICAR CUANTOS OBJETOS ESTAN VALIDOS O INVALIDOS
SELECT STATUS, COUNT(*) FROM USER_OBJECTS GROUP BY STATUS;

-- VERIFICAR LOS OBJETOS INVALIDOS
SELECT * FROM USER_OBJECTS WHERE STATUS='INVALID';